/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PushRouteImport } from './routes/push'
import { Route as PullRouteImport } from './routes/pull'
import { Route as LegsRouteImport } from './routes/legs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PushRoute = PushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRoute = PullRouteImport.update({
  id: '/pull',
  path: '/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const LegsRoute = LegsRouteImport.update({
  id: '/legs',
  path: '/legs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push': typeof PushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push': typeof PushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push': typeof PushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/legs' | '/pull' | '/push'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/legs' | '/pull' | '/push'
  id: '__root__' | '/' | '/about' | '/legs' | '/pull' | '/push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LegsRoute: typeof LegsRoute
  PullRoute: typeof PullRoute
  PushRoute: typeof PushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/push': {
      id: '/push'
      path: '/push'
      fullPath: '/push'
      preLoaderRoute: typeof PushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull': {
      id: '/pull'
      path: '/pull'
      fullPath: '/pull'
      preLoaderRoute: typeof PullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legs': {
      id: '/legs'
      path: '/legs'
      fullPath: '/legs'
      preLoaderRoute: typeof LegsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LegsRoute: LegsRoute,
  PullRoute: PullRoute,
  PushRoute: PushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
