/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Push2RouteImport } from './routes/push2'
import { Route as Push1RouteImport } from './routes/push1'
import { Route as PullRouteImport } from './routes/pull'
import { Route as LegsRouteImport } from './routes/legs'
import { Route as DietRouteImport } from './routes/diet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const Push2Route = Push2RouteImport.update({
  id: '/push2',
  path: '/push2',
  getParentRoute: () => rootRouteImport,
} as any)
const Push1Route = Push1RouteImport.update({
  id: '/push1',
  path: '/push1',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRoute = PullRouteImport.update({
  id: '/pull',
  path: '/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const LegsRoute = LegsRouteImport.update({
  id: '/legs',
  path: '/legs',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diet': typeof DietRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push1': typeof Push1Route
  '/push2': typeof Push2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diet': typeof DietRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push1': typeof Push1Route
  '/push2': typeof Push2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/diet': typeof DietRoute
  '/legs': typeof LegsRoute
  '/pull': typeof PullRoute
  '/push1': typeof Push1Route
  '/push2': typeof Push2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/diet' | '/legs' | '/pull' | '/push1' | '/push2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/diet' | '/legs' | '/pull' | '/push1' | '/push2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/diet'
    | '/legs'
    | '/pull'
    | '/push1'
    | '/push2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DietRoute: typeof DietRoute
  LegsRoute: typeof LegsRoute
  PullRoute: typeof PullRoute
  Push1Route: typeof Push1Route
  Push2Route: typeof Push2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/push2': {
      id: '/push2'
      path: '/push2'
      fullPath: '/push2'
      preLoaderRoute: typeof Push2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push1': {
      id: '/push1'
      path: '/push1'
      fullPath: '/push1'
      preLoaderRoute: typeof Push1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull': {
      id: '/pull'
      path: '/pull'
      fullPath: '/pull'
      preLoaderRoute: typeof PullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legs': {
      id: '/legs'
      path: '/legs'
      fullPath: '/legs'
      preLoaderRoute: typeof LegsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DietRoute: DietRoute,
  LegsRoute: LegsRoute,
  PullRoute: PullRoute,
  Push1Route: Push1Route,
  Push2Route: Push2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
